# -*- coding: utf-8 -*-
"""_journal_style.py —— Elsevier投稿级图件样式模块
==========================================================
期刊投稿硬性规格:
  - 单栏宽 90mm / 双栏宽 190mm,高度不超 230mm
  - 字号按最终印刷尺寸 7-8pt(不是画布尺寸)
  - 线宽 0.75-1.0pt
  - 无衬线字体(Arial/Helvetica/DejaVu Sans),与正文 Times 区分
  - 矢量 PDF(主)+ PNG 600dpi(预览)
  - 面板编号 (a)(b) 置于左上角,粗体
  - 图内文字一律英文(硬性要求,非润色)

输出到 reports/figures/journal/(不与 reports/figures/ 下的内部评审图混放),
caption 写入独立的 reports/figures/journal/captions_en.md /
_captions_en.json,与内部评审图的 captions.md 完全分离。

颜色/marker 复用 scripts/figs/_style.py 的 PRECURSOR_COLOR /
PRECURSOR_MARKER / TEMP_COLOR(色盲安全双编码,不在此处重新定义)。
"""
from __future__ import annotations

import inspect
import json
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
import pandas as pd

# 复用内部评审图的配色/marker 字典(不重新定义,保持双编码一致)
from _style import PRECURSOR_COLOR, PRECURSOR_MARKER, TEMP_COLOR  # noqa: F401

REPO_ROOT = Path(__file__).resolve().parents[3]
JOURNAL_DIR = REPO_ROOT / "reports" / "figures" / "journal"
CAPTIONS_MD = JOURNAL_DIR / "captions_en.md"
CAPTIONS_JSON = JOURNAL_DIR / "_captions_en.json"
SOURCE_DATA_DIR = REPO_ROOT / "manuscript" / "figures" / "source_data"
SOURCE_DATA_INDEX = SOURCE_DATA_DIR / "index.csv"

MM_PER_IN = 25.4
SINGLE_COL_MM = 90.0
DOUBLE_COL_MM = 190.0
MAX_HEIGHT_MM = 230.0


def mm_to_in(mm: float) -> float:
    return mm / MM_PER_IN


def single_column_figsize(height_mm: float) -> tuple[float, float]:
    assert height_mm <= MAX_HEIGHT_MM, f"height {height_mm}mm exceeds 230mm limit"
    return mm_to_in(SINGLE_COL_MM), mm_to_in(height_mm)


def double_column_figsize(height_mm: float) -> tuple[float, float]:
    assert height_mm <= MAX_HEIGHT_MM, f"height {height_mm}mm exceeds 230mm limit"
    return mm_to_in(DOUBLE_COL_MM), mm_to_in(height_mm)


def apply_journal_style() -> None:
    matplotlib.rcParams.update({
        "figure.dpi": 150,
        "savefig.dpi": 600,
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
        "font.size": 8,
        "axes.titlesize": 8,
        "axes.labelsize": 8,
        "xtick.labelsize": 7,
        "ytick.labelsize": 7,
        "legend.fontsize": 7,
        "lines.linewidth": 1.0,
        "lines.markersize": 4.5,
        "axes.linewidth": 0.75,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "grid.linewidth": 0.5,
        "legend.frameon": False,
        "savefig.bbox": "tight",
        "axes.unicode_minus": True,  # 图内文字全英文,不需要中文负号兼容
        "pdf.fonttype": 42,  # 矢量 PDF 里文字保持可编辑/可选中(TrueType),不转曲线
        "ps.fonttype": 42,
    })


apply_journal_style()


def add_panel_label(ax, label: str) -> None:
    """在子图左上角加粗体面板编号,如 '(a)'。用 axes 坐标(0,1)定位,
    不随数据范围变化,置于图外上方避免遮挡数据。"""
    ax.text(-0.02, 1.05, label, transform=ax.transAxes, fontsize=9,
           fontweight="bold", va="bottom", ha="right")


def save_fig_journal(fig, name: str, caption_en: str, panel_labels: bool = True) -> None:
    """保存为 reports/figures/journal/{name}.pdf(矢量)与 .png(600dpi),
    caption(英文)写入独立的 journal captions 文件,不触碰内部评审图的
    reports/figures/captions.md。

    panel_labels: 保留位供调用方标注该图是否已手动加过面板编号
    (add_panel_label),本函数不做隐式面板编号处理,仅记录/透传。
    """
    JOURNAL_DIR.mkdir(parents=True, exist_ok=True)
    pdf_path = JOURNAL_DIR / f"{name}.pdf"
    png_path = JOURNAL_DIR / f"{name}.png"
    fig.savefig(pdf_path)
    fig.savefig(png_path, dpi=600)
    _update_caption_en(name, caption_en)
    print(f"[save_fig_journal] {name}: {pdf_path.name} + {png_path.name}"
          f" (panel_labels={panel_labels})")


def save_fig_journal_tiff(fig, name: str) -> None:
    """SEM 位图面板另存 >=300dpi TIFF(除 PDF/PNG 外的额外要求)。"""
    JOURNAL_DIR.mkdir(parents=True, exist_ok=True)
    tiff_path = JOURNAL_DIR / f"{name}.tiff"
    fig.savefig(tiff_path, dpi=600, format="tiff")
    print(f"[save_fig_journal_tiff] {name}: {tiff_path.name}")


def _update_caption_en(name: str, caption_en: str) -> None:
    entries = {}
    if CAPTIONS_JSON.exists():
        entries = json.loads(CAPTIONS_JSON.read_text(encoding="utf-8"))
    entries[name] = caption_en
    CAPTIONS_JSON.write_text(
        json.dumps(entries, ensure_ascii=False, indent=2), encoding="utf-8")
    lines = ["# Figure captions (English, journal submission set)\n",
            "> Auto-generated by scripts/figs/journal/*.py via save_fig_journal().\n"]
    for n, c in entries.items():
        lines.append(f"\n## {n}\n\n{c}\n")
    CAPTIONS_MD.write_text("\n".join(lines), encoding="utf-8")


def skip(name: str, reason: str) -> None:
    print(f"[skip] {name}: {reason}")


_INDEX_COLUMNS = ["fig_name", "panel", "csv_path", "n_rows", "columns",
                  "source_files", "script", "note"]


def dump_source_data(fig_name: str, panel: str, df: pd.DataFrame | None = None, *,
                     note: str | None = None,
                     source_files: list | None = None) -> Path | None:
    """Write one figure panel's plotted-value tidy table to
    manuscript/figures/source_data/{fig_name}__{panel}.csv, and upsert its
    row into manuscript/figures/source_data/index.csv (keyed on
    (fig_name, panel) -- re-running a fig script updates its own rows in
    place rather than appending duplicates).

    df=None registers an index-only row with no CSV (csv_path left blank) --
    use this for a panel whose content is not tabular (e.g. a raw SEM image
    panel); state what the panel shows and why there is no table in `note`.

    Values in df must already be in the exact units/scale that get handed to
    the matplotlib call for this panel (e.g. already multiplied by 100 for a
    percent-axis bar chart) -- scripts/41_verify_figure_source_data.py
    compares this CSV byte-for-byte (1e-9 tolerance) against what the
    rendered artist actually shows, not against an unscaled source object.

    `script` (which fig*.py produced this panel) is recorded automatically
    from the caller's file path -- callers do not pass it.
    """
    SOURCE_DATA_DIR.mkdir(parents=True, exist_ok=True)
    caller_file = Path(inspect.stack()[1].filename).resolve()
    try:
        script_rel = caller_file.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        script_rel = caller_file.as_posix()

    if df is None:
        csv_path = None
        csv_rel = ""
        n_rows = 0
        columns_str = ""
    else:
        csv_path = SOURCE_DATA_DIR / f"{fig_name}__{panel}.csv"
        df.to_csv(csv_path, index=False)
        try:
            csv_rel = csv_path.relative_to(REPO_ROOT).as_posix()
        except ValueError:
            csv_rel = csv_path.as_posix()
        n_rows = len(df)
        columns_str = ";".join(df.columns)

    def _rel_source_file(f):
        p = Path(f)
        # For relative paths, join to REPO_ROOT directly without .resolve() to avoid
        # following symlinks (important in worktrees with junction-linked data/ subdirs).
        if not p.is_absolute():
            p = REPO_ROOT / p
        # For absolute paths, try to make them relative first (before resolving), in case
        # they contain symlinks that shouldn't be followed (e.g., junctions in worktrees).
        try:
            return p.relative_to(REPO_ROOT).as_posix()
        except ValueError:
            # Path is not relative to REPO_ROOT; try resolving it and check again
            p = p.resolve(strict=False)
            try:
                return p.relative_to(REPO_ROOT).as_posix()
            except ValueError:
                # Path is outside REPO_ROOT (and stays outside after resolving); return absolute
                return p.as_posix()

    source_files_str = ";".join(_rel_source_file(f) for f in (source_files or []))
    _update_source_data_index(fig_name, panel, csv_rel, n_rows, columns_str,
                              source_files_str, script_rel, note or "")
    print(f"[dump_source_data] {fig_name}__{panel}: "
         f"{csv_rel or '(no csv)'} ({n_rows} rows)")
    return csv_path


def _update_source_data_index(fig_name: str, panel: str, csv_rel: str, n_rows: int,
                              columns_str: str, source_files_str: str,
                              script_rel: str, note: str) -> None:
    if SOURCE_DATA_INDEX.exists():
        idx = pd.read_csv(SOURCE_DATA_INDEX, keep_default_na=False)
    else:
        idx = pd.DataFrame(columns=_INDEX_COLUMNS)

    row = {
        "fig_name": fig_name, "panel": panel, "csv_path": csv_rel,
        "n_rows": n_rows, "columns": columns_str,
        "source_files": source_files_str, "script": script_rel, "note": note,
    }
    mask = (idx["fig_name"] == fig_name) & (idx["panel"] == panel)
    if mask.any():
        for k, v in row.items():
            idx.loc[mask, k] = v
    else:
        idx = pd.concat([idx, pd.DataFrame([row])], ignore_index=True)
    idx = idx.sort_values(["fig_name", "panel"]).reset_index(drop=True)
    SOURCE_DATA_DIR.mkdir(parents=True, exist_ok=True)
    idx.to_csv(SOURCE_DATA_INDEX, index=False)
